//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTime3.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTime3.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading user list.
        /// </summary>
        internal static string CTimeService_ErrorWhileLoadingAttendanceList {
            get {
                return ResourceManager.GetString("CTimeService.ErrorWhileLoadingAttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading current time.
        /// </summary>
        internal static string CTimeService_ErrorWhileLoadingCurrentTime {
            get {
                return ResourceManager.GetString("CTimeService.ErrorWhileLoadingCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading times.
        /// </summary>
        internal static string CTimeService_ErrorWhileLoadingTimes {
            get {
                return ResourceManager.GetString("CTimeService.ErrorWhileLoadingTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while login.
        /// </summary>
        internal static string CTimeService_ErrorWhileLogin {
            get {
                return ResourceManager.GetString("CTimeService.ErrorWhileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while stamp.
        /// </summary>
        internal static string CTimeService_ErrorWhileStamp {
            get {
                return ResourceManager.GetString("CTimeService.ErrorWhileStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Entered {
            get {
                return ResourceManager.GetString("Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeOffice.
        /// </summary>
        internal static string HomeOffice {
            get {
                return ResourceManager.GetString("HomeOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortBreak.
        /// </summary>
        internal static string ShortBreak {
            get {
                return ResourceManager.GetString("ShortBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        internal static string Trip {
            get {
                return ResourceManager.GetString("Trip", resourceCulture);
            }
        }
    }
}
